# -*- coding: utf-8 -*-
"""CURSO EM VIDEO PYTHON MUNDO 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ZFmBoUl7klMmp0Q1mw3difddE9KIEk6
"""

#  A função print() serve para imprimir os argumentos passados a ela no terminal.
# Usa-se '' ou "" para imprimir caracteres do tipo string.--> print('str')
# para números e variáveis não usamos aspas.--> print()

# Crie um programa que mostre 'Ola, mundo!' na tela.

print ('Olá, Mundo!')

# A Função input()

#  A função input() faz uma pausa no programa e espera uma entrada do usuário pelo terminal. Para ler a entrada do usuário
# a função input() espera que após digitada a entrada o usuário aperte a tecla enter, após isso input()
# lê essa entrada como uma string, portanto, se a entrada esperada for um número ela deve ser convertida
# usando-se as funções de conversão int() ou float().

# ex-001 Escreva um programa que leia um nome e mostre uma mensagem de boas vindas.

#  Criando uma variável chamada 'nome' do tipo string, que recebe o input do usuário. Após digitado os dados, pressionado
# enter, aparece uma mensagem de boas vindas na tela.

nome = input(str('Qual seu nome ? '))
print ('Ola,', nome , 'seja muito bem vindo!')

# Ex-002 Crie um programa que o dia, o mes e o ano de nascimento de uma pessoa e mostre uma mensagem com a data formatada.

#  Criando 3 variáveis de entrada de dados: dia, mes, ano. Logo após é mostrado uma mensagem na tela, usandos os dados
# inseridos nas mesmas.

dia = input(str('Dia:'))
mes = input(str('Mes:'))
ano = input(str('Ano:'))
print(f'Voce nasceu no dia {dia} de {mes} de {ano}, correto?')

# Ex-003 Crie um programa que leia dois numeros e mostre a soma entre eles.

# Criando as variaves de entrada n1 e n2 do tipo float ( Números decimais ).

n1 = float(input('Digite o primeiro número:'))
n2 = float(input('Digite o segundo número numero:'))

# Imprimindo a soma.
print(f'A soma entre {n1} + {n2} é: {n1+n2}')

# Ex-004 Discecando uma variavel.

# criando a variável X.
x = input('Digite qualquer coisa: ')

# Imprimindo o que tem dentro de X
print(f'Você escreveu {x}')

# Vendo qual o tipo de X.
print('Qual é o tipo: ', type(x))

# Vendo se X é alfanumérico.
print('Ele é alfanumérico? ', x.isalnum())              

# Vendo se X é numérico.
print('Ele é númerico? ', x.isnumeric())                 

# Vendo se X é alfabético.
print('Ele é alfabético? ', x.isalpha())                 

# Vendo se X está em minúsculo.
print('Ele está em letras minúsculas? ', x.islower())    

# Vendo se X está em maiúsculo.
print('Ele está em letras maiúsculas? ', x.isupper())    

# Vendo se X é imprimível.
print('Ele é imprimível? ', x.isprintable())

# Vendo se X é um espaço.
print('Ele é um espaço? ', x.isspace())                  

# Vendo se X é um dígito.
print('Ele é um dígito? ', x.isdigit())

# Imprimindo 'Fim', na tela.
print('Fim!')

# ex-005 escreva um programa que leia um numero e mostre na tela o seu antecessor e o seu sucesso.

# Criando a variável 'num' do tipo inteiro.
num = int(input('Digite um número: '))

# antecessor: num -1
# sucessor: num +1

print(f'Voce digitou {num} , seu antecessor é {num - 1}, e seu sucessor é {num +1} . ')

# ex-006 Escreva um programa que leia um numero e mostre seu dobro, tripulo e raiz quadrada.

# Criando a variável de entrada 'num' do tipo inteiro.

num = int(input('Digite um numero: '))

# Dobro: num * 2
# Triplo: num * 3
# Raiz: num ** 0.5

print(f'Voce digitou {num}, seu dobro é {num * 2}, seu triplo é {num * 3} e sua raiz quadrada é {num ** (1/2)} .')

# ex-007 Escreva um programa que leia duas notas de um aluno e mostre sua media.

# Criando as variáveis de entrada: nota1, nota2.
nota1 = float(input('Digite a primeira nota: '))
nota2 = float(input('Digite a segunda nota: '))

# Criando a variável que recebe o cálculo da média.
media = (nota1 + nota2) / 2

# Imprimindo o resultado.
print(f'A média entre suas notas é: {media} ')

# ex-008 Escreva um programa que leia um valor em metros e o exiba convertido em centímetros e milímetros.

# Criando a variável de entrada.
metros = float(input('Digite um valor em metros: '))

# Criando as variáveis de cálculo.
centimetros = metros * 100
milimetros = metros * 1000

# Imprimindo o resultado.
print(f'O valor de {metros} métro(s), em centímetros é {centimetros} cm, e em milímetros é {milimetros} mm .')

# ex-009  Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.

# Criando a variável que recebe o valor para cálcular sua tabuada. 
tabuada = int(input('Digite um valor qualquer que eu mostro sua tabuada: '))

# Imprimindo o número à calcular.
print(f'A tabuada de {tabuada} é:')

# Imprimindo o número multipicado de 1 até 10. e uma mensagem de 'FIM' no final.
print(f'{tabuada} x 1 = {tabuada * 1}')
print(f'{tabuada} x 2 = {tabuada * 2}')
print(f'{tabuada} x 3 = {tabuada * 3}')
print(f'{tabuada} x 4 = {tabuada * 4}')
print(f'{tabuada} x 5 = {tabuada * 5}')
print(f'{tabuada} x 6 = {tabuada * 6}')
print(f'{tabuada} x 7 = {tabuada * 7}')
print(f'{tabuada} x 8 = {tabuada * 8}')
print(f'{tabuada} x 9 = {tabuada * 9}')
print(f'{tabuada} x 10= {tabuada * 10}')
print('FIM!')

# ex-010 Crie um programa que leia quanto dinheiro uma pessoa tem na carteira e mostre quantos dólares ela pode comprar.

# Criando as  variáveis de entrada, do tipo float.
reais = float(input('Quantos reais voce possui em sua carteira? '))
cotaçao = float(input('Digite o valor da cotação do dólar hoje? '))

# Variável que recebe o cálculo.
dolar = reais / cotaçao

# ' :.2f ' exibe o número com apenas 2 casas decimais.
print(f'Com {reais} R$ você consegue comprar {dolar:.2f} Us$ !')

# ex-011 Faça um programa que leia a largura e a altura de uma parede em metros, calcule a sua área e a quantidade de tinta necessária para pintá-la, sabendo que cada litro de tinta pinta uma área de 2 metros quadrados.

# Variáveis de entrada.
largura = float(input('Digite a largura da parede: '))
altura = float(input('Digite a altura da parede: '))

# Variavel que recebe a litragem de tinta por Metro Quadrado.
tinta = 2

# variável que calcula metros quadrados.
metros_quadrados = largura * altura   

# Variável que calcula a litragem total de tinta.
litros_de_tinta = metros_quadrados / tinta

print(f'Sua parede tem {metros_quadrados:.2f} metros quadrados, para pinta-la você vai precisar de {litros_de_tinta:.2f} Litros de tinta. ')

# ex-012 Faça um algoritmo que leia o preço de um produto e mostre seu novo preço, com 5% de desconto.

produto = float(input('Digite o valor do produto desejado: '))

# Variável que calcula 5% de produto.
porcentagem = (produto - ((produto * 5) / 100))

print(f'O valar do produto é {produto} R$, e com desconto de 5% fica {porcentagem} R$ .')

# ex-013 Faça um algoritmo que leia o salário de um funcionário e mostre seu novo salário, com 15% de aumento.

# Variáveis de entrada.
funcionario = input('Digite o nome do funcionário: ')
salario = float(input(f'digite o salário de {funcionario}: '))

# Variável de calculo de porentagem.
salarionovo = (salario + (salario * 15) /100)

print(f'O salário atual de {funcionario} é de {salario} R$, e com um aumento de 15% ficara em, {salarionovo} R$ . ')

# ex-014 Escreva um programa que converta uma temperatura digitando em graus Celsius e converta para graus Fahrenheit.

celsius = float(input('Digite a temperatura em graus celsius:'))
fahrenheit = (celsius * 1.8) + 32
print(f'A temperatuda de {celsius} °C graus celsius, em fahrenheit fica {fahrenheit:.1f} °F graus.')

'''
ex-015 Escreva um programa que pergunte a quantidade de Km percorridos por um carro alugado e a quantidade 
de dias pelos quais ele foi alugado. Calcule o preço a pagar, sabendo que o carro custa R$60 por dia e R$0,15 por Km rodado.
'''

# Variável que recebe os dias pelo usuário.
dias = float(input('Quantos dias você ficou com o veiculo? '))

# Variável que calcula o valor da diária.
vdia = 60 * dias

# Variável que recebe a quilometragem.
km = float(input('Quantos km você rodou com o veículo? '))

# Variável que calcula o valor da quilometragem.
vkm = 0.15 * km

print(f'Voce rodou {km} km em {dias} dias, o valor total de sua despesa é de {vdia + vkm } R$ . ')

# Ex-16 Crie um programa que leia um número Real qualquer pelo teclado e mostre na tela a sua porção Inteira.

# Importando o módulo math

import math 

# Variável que recebe o número real.
numero = float(input('Digite um númetro: '))

# Usando a funçãon math.trunc() na variável 'numero', para mostar apenas a parte inteira do número digitado.
print(f'Voce digitou {numero}, sua parte inteira é {math.trunc(numero)}.')

# Ex-17 Faça um programa que leia o comprimento do cateto oposto e do cateto adjacente de um triângulo retângulo. Calcule e mostre o comprimento da hipotenusa.


# Importando a função hypot do módulo math.

from math import hypot

cat_o = float(input('Digite o valor do cateto oposto: '))
cat_adj = float(input('Digite o valor do cateto adjacente: '))

# Variavel que recebe o cálculo da hypotenusa, usando a ' função hypot() '.

hipo = hypot(cat_o , cat_adj)

print(f'O valor da hipotenusa é: {hipo:.2f}')

# Ex-18 Faça um programa que leia um ângulo qualquer e mostre na tela o valor do seno, cosseno e tangente desse ângulo.

# Importando o módulo math

import math 

# Variável que recebe ângulo.
angulo = float(input('Digite um angulo: '))

# Trânsformando angulo em radianos.
radiano = math.radians(angulo)

# Descorindo o seno.
seno = math.sin(radiano)

# Descobrindo o cosseno. 
cosseno = math.cos(radiano)

# Descobrindo a tangente.
tangente = math.tan(radiano)

# Imprimindo o resultado.
print(f'Voce digitou o  Angulo de {angulo} Graus, seu seno é {seno:.3f}, seu cosseno é {cosseno:.3f}, e sua tangente é {tangente:.3f}')

# Ex-19 Um professor quer sortear um dos seus quatro alunos para apagar o quadro. Faça um programa que ajude ele, lendo o nome dos alunos e escrevendo na tela o nome do escolhido.

# Importando o módulo random
import random

# Recebendo o nome dos 4 alunos.
aluno_1 = str(input('Primeiro nome: '))
aluno_2 = str(input('Segundo nome: '))
aluno_3 = str(input('Terceiro nome: '))
aluno_4 = str(input('Quarto nome: '))

# Criando uma lista ' alunos[] 'com o nome dos alunos.
alunos = [aluno_1, aluno_2, aluno_3, aluno_4]

# Sorteando um aluno dentro da lista, com a função random.choices(alunos) .
sorteio = random.choices(alunos)

# Imprimindo o aluno sorteado.
print(f'O aluno escolhido foi: {sorteio}')

# Ex-20 O mesmo professor do desafio 19 quer sortear a ordem de apresentação de trabalhos dos alunos. Faça um programa que leia o nome dos quatro alunos e mostre a ordem sorteada.

# Importando a função ' shuffle() ' do módulo random.
from random import shuffle

# Recebendo os 4 alunos.
aluno_1 = str(input('Primeiro nome: '))
aluno_2 = str(input('Segundo nome: '))
aluno_3 = str(input('Terceiro nome: '))
aluno_4 = str(input('Quarto nome: '))

# Criando uma lista ' alunos = [] ' dos alunos. 
alunos = [aluno_1, aluno_2, aluno_3, aluno_4]

# Sorteando os alunos, com a função shuffle() .
shuffle(alunos)

# Imprimindo o resultado.
print(f'A ordem de apresentacao escolhida foi: {alunos}')

# Ex-21  Faça um programa em Python que abra e reproduza o áudio de um arquivo MP3.
# testar no VSCODE ou no PYCHARM!!!

# Importando playsound
from playsound import playsound

# Inicializando o a funçã playsound()
# Reprodusindo...
playsound('musica.mp3')

''' Ex-22 Crie um programa que leia o nome completo de uma pessoa e mostre:

– O nome com todas as letras maiúsculas e minúsculas.

– Quantas letras ao todo (sem considerar espaços).

– Quantas letras tem o primeiro nome.  '''


# Criando a variável nome + função .strip()
# .strip() RETIRA OS ESPACOS DO COMECO E DO FIM.
nome = str(input('Digite seu nome completo: ')) .strip()

# Transforma em maiusculo.
print(f'Seu nome Maiúsculos: {nome.upper()}.') 

# Transforma em minusculo.
print(f'Seu nome Minúsculo: {nome.lower()}.') 

# Le os caracteres de nome - os espacos contados por nome.count(' ').
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")} letras.') 

# Procura quantas letras tem ate o primeiro espaco!
print(f'Seu primeiro nome tem {nome.find( " " )} letras. ')          

    # Ou usando o metodo split...
    #  Cria uma lista do conteudo da variavel nome, na variavel separa.

#separa = nome.split()  
#print(f'Seu primeiro nome é {separa[0]}, e ele tem {len(separa[0])} letras.')

# Ex-23 Faça um programa que leia um número de 0 a 9999 e mostre na tela cada um dos dígitos separados.

# Recebendo o número pelo usuário.
numero = int(input('Digite um numero: '))

# Imprimindo o conteúdo de numero.
print(f'Analizando o numero {numero}...')

# Separando a unidade: DIVIDE A PARTE INTEIRA POR 1, DIVIDE POR 10 E PEGA O RESTO.
unidade = numero // 1 % 10 

# Separando a dezena: DIVIDE A PARTE INTEIRA POR 10, DIVIDE POR 10 E PEGA O RESTO. 
dezena = numero // 10 % 10  

# Separando a centena: DIVIDE A PARTE INTEIRA POR 100, DIVIDE POR 10 E PEGA O RESTO.
centena = numero // 100 % 10     

# Separando a milhar: DIVIDE A PARTE INTEIRA POR 1000, DIVIDE POR 10 E PEGA O RESTO.
milhar = numero // 1000 % 10     

# Imprimindo o número separadamente.
print(f'Unidade: {unidade}')
print(f'Dezena: {dezena}')
print(f'Centena: {centena}')
print(f'Milhar: {milhar}')

# Ex-24 Crie um programa que leia o nome de uma cidade diga se ela começa ou não com o nome “SANTO”.

# Recebendo o nome da cidade.
# usando a função .strip() para eliminar todos os espacos do comeco e do fim da string.
cidade = str(input('Em que cidade voce nasceu? ')) .strip()  

# Transforma os caracteres de 0 a 4 em maiúsculos e compara se é igual a SANTO.
print(cidade[:5] .upper() == 'SANTO')

# Ex-25  Crie um programa que leia o nome de uma pessoa e diga se ela tem “SILVA” no nome.

# Recebendo nome descartando os espaços do início e do fim.
nome = str(input('Digite seu nome completo: ')).strip()

# Jogando o valor de nome para maiúsculo.
nome = nome.upper()

# Verificando se tem SILVA no conteúdo de nome.
print(f'Voce possui Silva em seu nome? {"SILVA" in nome}')

'''
 Ex-26 Faça um programa que leia uma frase pelo teclado e mostre quantas vezes aparece a letra “A”,
em que posição ela aparece a primeira vez e em que posição ela aparece a última vez.
'''

# Recebendo a frase descartando os espaços do início e do fim.
frase = str(input('Digite aqui sua frase: ')).strip()

# Transformando o conteudo de frase em maiúsculo
frase = frase.upper()

# Verificando quantas letras A tem no conteúdo de frase.
print(f'A frase: {frase}, tem {frase.count("A")} letras A.' )

# Encontrando a posição do primeiro A .
print(f'O primeiro A se encontra na posicao: {frase.find("A")+1}.')

# Encontrando a posição do ultimo A . 
print(f'O ultimo A se encontra na posicao: {frase.rfind("A")+1}.')

# Ex-27 Faça um programa que leia o nome completo de uma pessoa, mostrando em seguida o primeiro e o último nome separadamente.

# Recebendo o nome do usuário.
nome = str(input('Digite seu nome completo: '))

# Imprimindo o conteúdo de nome.
print(f'Olá, {nome}.' )

# Criando uma lista com o conteúdo de nome, separando em ítens com a função  split() .
lista = nome.split()

# Exemplo:
#     print(lista)
#       ['Vinícius', 'Bitencourt', 'Pereira']

# Imprime o item 1 e o ultimo item da lista -1.
print(f'Seu primeiro nome é {lista[0]}, e seu ultimo nome é {lista[-1]}.')

''' EX-28 Escreva um programa que faça o computador “pensar” em um número inteiro entre 0 e 5 e peça para o usuário tentar 
descobrir qual foi o número escolhido pelo computador. O programa deverá escrever na tela se o usuário venceu ou perdeu.'''

# Importando a função randint do módulo random
from random import randint

# Importando a função sleep do módulo time
from time import sleep

# Criando uma mensagem inicial do jogo.
print('E ai, bora jogar? Eu vou pensar em um numero de 0 á 5 e voce tem que adivinhar...')

# Recebendo um número aleatório de 0 a 5 do usuário.
player = int(input('Digite o numero que estou pensando: '))

# CPU escolhendo um número aleatório entre 0 e 5.
resposta = randint(0,5)

# Imprimindo PROCESSANDO...   com 1.5 segundos de delay.
print('PROCESSANDO...')
sleep(1.5)

# Comparando a resposta do Jogador com a da CPU. 
#   Imprime o resultado!
if player == resposta :
  print('Voce ganhou!')
  print(f'Eu pensei no número {resposta}.')
else :
  print('Game Over!')
  print(f'A resposta certa era {resposta}.')
  print('Tente outra vez')

'''
 Ex- 29 Escreva um programa que leia a velocidade de um carro. Se ele ultrapassar 80Km/h, mostre uma 
mensagem dizendo que ele foi multado. A multa vai custar R$7,00 por cada Km acima do limite.
'''
# Recebendo a velocidade atual do carro.
v_atual = int(input('Em que velocidade voce esta? '))

# Velocidade limite da via: 80km/h
v_limit = 80

# Multa p/ cada km acima de 80km/h: 7 R$
multa = 7.00  

# Valor total da multa se a velocidade estiver acima do permitido.
multa_total = (v_atual - v_limit) * multa

# Verificando se a velocidade atual esta dentro do limite.
if v_atual > v_limit :
   print(f'ATENCAO!!! Voce está acima da velocidade permitida que é de {v_limit} KM/h. ')
   print(f'Voce foi multado em {multa_total} R$.')
else:
  print('Siga com prudencia, Boa Viagem!.')

# Ex- 30 Crie um programa que leia um número inteiro e mostre na tela se ele é PAR ou ÍMPAR.

# Recebendo um número do usuário.
numero = int(input('Digite um número:')) 

# Descobrindo se o número é par:
#    Se o resto da divisao p/ 2 é igual a 0 então ele é par.
#     senao é impar.

if (numero % 2) == 0 :
  print(f'{numero} é par.')
else:
  print(f'{numero} é impar.')

'''
Ex-31 Desenvolva um programa que pergunte a distância de uma viagem em Km. Calcule o preço da passagem,
 cobrando R$0,50 por Km para viagens de até 200Km e R$0,45 parta viagens mais longas.
'''
# Recebendo a distância da viagem em km. 
distancia = float(input('Qual a distancia da sua viagem em km? '))

# Para distâncias longas, R$ 0.45
distancia_longa = distancia * 0.45

# Para distância curta, R$ 0.50
distancia_curta = distancia * 0.50

# Comparando a distância e imprimindo o resultado após.
if distancia <= 200:
  print(f'O valo de sua viagem será {distancia_curta:.2f} R$.')
else :
  print(f'O valor de sua passagem será {distancia_longa:.2f} R$')

# EX- 32 Faça um programa que leia um ano qualquer e mostre se ele é bissexto.

# Importando a função date do módulo datetime.
from datetime import  date

# Recebendo o ano do usuário.
ano = int(input('Digite um ano: '))

# Variável que recebe o ano atual.
ano_atual = date.today().year

# Comparando se o ano é bisexto ou não. Após imprime o resultado.

# Se o usuário digitar 0, é exibido o ano atual.
if ano == 0:
   ano = ano_atual
'''
 Para saber se um ano é bissexto existe uma regra básica:
  * Tem que ser múltiplos de 4 .                 ( ano % 4 == 0   )
  * Esses anos não podem ser múltiplos de 100 .  ( ano % 100 != 0 )
  * Podem ser múltipos de 400 .                  ( ano % 400 == 0 )
'''
if ano % 4 == 0 and ano % 100 != 0 or ano % 400 == 0 :
  print(f'O ano de {ano} é bissexto.')
else :
  print(f'O ano de {ano} nao é bissexto.')

# Ex- 33 Faça um programa que leia três números e mostre qual é o maior e qual é o menor.

# Recebendo 3 números do usuário.
n1 = float(input('Digite o primeiro numero: '))
n2 = float(input('Digite o segundo numero: '))
n3 = float(input('Digite o terceiro numero: '))

# Imprimindo os 3 números
print(f'Voce digitou {n1, n2, n3}.')

# verificando quem é o menor
# Setando n1 como menor para verificar apenas n2 e n3 .
menor = n1
if n2<n1 and n2<n3:
  menor = n2
if n3<n1 and n3<n2:
  menor = n3

# verificando quem é o maior
# Setando n1 como maior para verificar apenas n2 e n3 .
maior = n1
if n2>n1 and n2>n3:
  maior = n2
if n3>n2 and n3>n1:
  maior = n3

# Imprimindo o resultado.
print(f'O menor número é {menor}.')
print(f'O maior número é {maior}.')

'''
Ex- 34 Escreva um programa que pergunte o salário de um funcionário e calcule o valor do seu aumento. 
Para salários superiores a R$1250,00, calcule um aumento de 10%. Para os inferiores ou iguais, o aumento é de 15%.
'''

# Recebendo o salário do usuário.
salario = float(input('Digite seu salário: '))

# Para salários <= RS 1250.00, o aumento é de 15% .
aumento_maior = (salario + ((salario * 15) / 100))

# Para salários > RS 1250.00, o aumento é de 10% .
aumento_menor = (salario + ((salario * 10) / 100))

# Verificando se salario é menor ou igual a R$ 1250.00. apos imprime o resultado.
if salario <= 1250.00 :

  print(f'Seu salário atual é de {salario:.2f} R$.')
  print(f'Seu salário com almento será de {aumento_maior:.2f} R$.')
else:
  print(f'Seu salário atual é de {aumento_menor:.2f} R$.')
  print(f'Seu salário com almento será de {salario + (salario * 10) / 100:.2f} R$.')

# Ex- 35 Desenvolva um programa que leia o comprimento de três retas e diga ao usuário se elas podem ou não formar um triângulo.

# Imprimindo um sublinhado antes e depois da frase ' print('=-'*30) '.
print('=-'*30)
print('ANALIZADOR DE TRIANGULOS...')
print('=-'*30)

# Reebendo os valores das retas a, b, c . 
a = float(input('Digite o valor da primeira reta:'))
b = float(input('Digite o valor da segunda reta:'))
c = float(input('Digite o valor da terceira reta:'))

'''
Condição de existência de triângulos:
  a soma de dois lados é sempre menor que o terceiro lado;
     a<b+c
     b<a+c
     c<a+b 
'''
# Comparando os valores das retas. Após imprime o resiltado.
if a<b+c and b<a+c and c<a+b :
  print('Você pode formar um triangulo com essas retas!')
else:
  print('Você nao pode formar um triangulo com essas retas!')